TCP: server, client, shell script.
DIT524-V17/group-7 pull request #10
Opened 2017-04-18 09:31 UTC by pontuslae

Server that runs on raspberry pi.
Client that runs on the android application.
Shell script that runs on the raspberry pi.
This only lacks the descripion on how the service was initialized.

2017-04-18 11:24 UTC, Sebastian-Fransson submitted a review, later dismissed

2017-04-18 11:24 UTC, Sebastian-Fransson commented on tcpclient/Client.java
> +			return "";
Return the 's' string instead of an empty one?

2017-04-18 11:47 UTC, timjon commented on tcpclient/Client.java
> +*/
Why is this comment here

2017-04-18 11:48 UTC, pontuslae commented on tcpclient/Client.java
> +*/
It's for a functionality not currently used after I altered the Android application to not require these.

2017-04-19 11:21 UTC, timjon commented on tcpclient/Client.java
> +	Transmitter(String host, int port) {
What does this do

2017-04-19 11:28 UTC, IsabelleTornqvist commented on tcpclient/Client.java
> +			in = new BufferedReader(new InputStreamReader(socket.getInputStream())); // I hate Java.
Should probably remove this comment

2017-04-20 09:49 UTC, timjon requested changes
The last things that needs to be checked

2017-04-20 09:49 UTC, timjon commented on tcpclient/Client.java
> +	Transmitter(String host, int port) {
Needs a comment on what this does

2017-04-20 09:49 UTC, timjon commented on tcpclient/Client.java
> +		// TODO: 06/03/2017 Add command vertification here. Preferably O(1).
Is this something that needs to be done or can it be removed?

2017-04-20 09:49 UTC, timjon commented on tcpclient/Client.java
> +	public void run() {}
Remove this?

2017-04-20 09:49 UTC, timjon commented on tcpclient/receiver.py
> +    msg = None
Not really needed but maybe a comment for line 17-22 for clarity

2017-04-21 11:14 UTC, timjon approved these changes

2017-04-21 11:15 UTC, merged