Switching sensors on and off
DIT524-V17/group-7 pull request #13
Opened 2017-04-21 11:12 UTC by IsabelleTornqvist

2017-04-21 11:19 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +boolean RIP = true;
All the activations use the suffix Activation but not this one.

2017-04-21 11:20 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    if (!sensors.getAddress(thermometer, 0)) Serial.println("Unable to find address for Device 0");
Why are you printing to the serial? Doesn't that get passed to the android client and cause issues?

2017-04-21 11:21 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +//Check temperature
Doesn't this convert the temperature to a string for sending it? not check it.

2017-04-21 11:22 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +int tempC;
Why is the temp variables declared next to the range and velocity? Are they related?

2017-04-21 11:23 UTC, timjon requested changes

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +boolean RIP = true;
Needs a comment to specify what this boolean is for

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +#include <OneWire.h> //https://github.com/PaulStoffregen/OneWire
Needs to be specified what this library does

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +#include <DallasTemperature.h> //https://github.com/milesburton/Arduino-Temperature-Control-Library
Needs to be specified what this library does

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    if (!sensors.getAddress(thermometer, 0)) Serial.println("Unable to find address for Device 0");
Why is there a serial.print here

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    sensors.begin();
What is this used for?

2017-04-21 11:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    sensors.requestTemperatures(); // Get temperatures
Needs a delay

2017-04-21 11:23 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +
At least make a comment for all of these cases.

2017-04-21 11:25 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +boolean RIP = true;
Full capital variable decleration. Please don't do this Tim.

2017-04-21 11:46 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +int tempC;
yes

2017-04-21 12:05 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    if (velocity < 90 && !motorActivation){
Shouldnt be not motorActivation

2017-04-21 12:06 UTC, timjon requested changes

2017-04-21 12:06 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    if (velocity < 90 && !motorActivation){
Shouldnt be a not motorActivation since then it wont do this while the motor is on

2017-04-24 08:08 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
Add a few line breaks here to seperate flame stuff from other stuff. So it's easier to locate it.

2017-04-24 08:34 UTC, timjon approved these changes

2017-04-24 08:36 UTC, pontuslae approved these changes
All my concerns have been adressed.

2017-04-24 10:34 UTC, ElaineQvarnstrom approved these changes

2017-04-24 10:35 UTC, merged