Camera servos
DIT524-V17/group-7 pull request #15
Opened 2017-04-24 11:25 UTC by pontuslae

2017-04-24 11:35 UTC, timjon requested changes

2017-04-24 11:35 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +const int analog1 = 55; // Analog pin 1
I dont understand what this pin is used for, change the name

2017-04-24 11:35 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      int value = input.substring(1, 4).toInt();
use input_Value instead, easier to understand

2017-04-24 11:38 UTC, IsabelleTornqvist requested changes

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +// Camera servos and all related code.
Has this been tested?
Test the current version of the code before requesting!

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +// Author: Pontus Laestadius.
Time stamp?

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    camera_servo_x.attach(analog0); //analog pin 0
What does this do? Add comments

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      // Their input should fit this expression: (x||y)(0001||0002)
Good job with this comment!

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +void cameraUpdate(int &x, int &y) {
What does &x/&y do?

2017-04-24 11:38 UTC, IsabelleTornqvist commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +
Looks ok, but has to be tested with the car and app before a merge! Test all sensors and modules!

2017-04-24 11:39 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      int value = input.substring(1, 4).toInt();
How about just calling it input.substring(1, 4).toInt(); since that was what it was before. ANd that was clear to understand

2017-04-24 11:40 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +void cameraUpdate(int &x, int &y) {
https://www.arduino.cc/en/reference/pointer

2017-04-24 11:41 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      // Their input should fit this expression: (x||y)(0001||0002)
(>'-')> <('-'<) ^('-')^ v('-')v(>'-')> (^-^)

2017-04-24 11:45 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +// Camera servos and all related code.
Stuff has indeed been tested.

2017-04-24 11:46 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +
Functionality with the phone has already been tested, Only requires integration testing and to see if all the existing features still work.

2017-04-24 11:50 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      int value = input.substring(1, 4).toInt();
Well im just making suggestions to make the code easier to read

2017-04-25 13:51 UTC, IsabelleTornqvist approved these changes

2017-04-25 13:51 UTC, timjon approved these changes

2017-04-26 09:26 UTC, ElaineQvarnstrom commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      case 'x': // Sets the command to be used in the update function.
Specify which update function, because what if someone else creates a update function

2017-04-26 09:28 UTC, ElaineQvarnstrom commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    return degrees < min ? min : max;
repetition of line 319

2017-04-26 09:30 UTC, ElaineQvarnstrom commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +void setCameraServoRelative(Servo &servo, const int &max, const int &min, int valueReceivedFromTheRaspberry, int &currentAngle) {
You have to explain this further to me irl and probably add commenting so it's more understandable.

2017-04-26 09:31 UTC, ElaineQvarnstrom requested changes
Mainly about understandability in the last method

2017-04-26 11:38 UTC, ElaineQvarnstrom approved these changes

2017-04-26 11:38 UTC, merged