CameraServoDeactivation
DIT524-V17/group-7 pull request #20
Opened 2017-05-08 08:41 UTC by IsabelleTornqvist

Deactivation/activation of camera servos X and Y. Refined temperature code.

2017-05-08 08:44 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        case 'X':
Add comment here

2017-05-08 08:44 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        case 'Y':
Add comment here

2017-05-08 08:45 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      //Serial.println("t");
unnecessary. Remove this

2017-05-08 08:50 UTC, timjon requested changes
No comment added for new version and what has been edited

2017-05-08 08:58 UTC, timjon requested changes

2017-05-08 08:58 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +boolean camera_servo_activation_vertical = true; //Y is vertical
Should be "camera_servo_horizontal_activation" and "camera_servo_vertical_activation for consistency"

2017-05-08 08:58 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +  String tempString = "t";
temp_string maybe?

2017-05-08 09:13 UTC, timjon approved these changes

2017-05-09 11:14 UTC, pontuslae approved these changes
Good job

2017-05-09 12:00 UTC, ElaineQvarnstrom approved these changes
Looking good!

2017-05-09 12:16 UTC, merged