GUI temp
DIT524-V17/group-7 pull request #25
Opened 2017-05-10 14:11 UTC by timjon

2017-05-10 14:18 UTC, Sebastian-Fransson approved these changes

2017-05-10 14:18 UTC, IsabelleTornqvist commented on F.R.O.S.T/app/src/main/java/t/s/o/r/f/frost/MainActivity.java
> +        fireImage = (ImageView)findViewById(R.id.imageView1);
Maybe have a space here? If they are not related to the stuff above. Maybe a comment/description

2017-05-10 14:20 UTC, IsabelleTornqvist approved these changes

2017-05-10 14:28 UTC, Anthony1911 requested changes
Add explanation for this section

2017-05-10 14:29 UTC, pontuslae commented on F.R.O.S.T/app/src/main/res/layout-land/activity_main.xml
> +        android:id="@+id/imageView1"
Sorry what is this imageview1????????
I'm stupid and don't understands.

2017-05-10 14:32 UTC, pontuslae commented on F.R.O.S.T/app/src/main/java/t/s/o/r/f/frost/MainActivity.java
> +                    if(s.charAt(3) == '1'){
This entire if statement just be, but It's just a suggestion.
fireImage.setVisibility(s.charAt(3) == '1' ? View.VISIBLE : View.INVISIBLE);

2017-05-11 12:48 UTC, Anthony1911 approved these changes

2017-05-11 12:50 UTC, merged