Decrease wear on the gear
DIT524-V17/group-7 pull request #27
Opened 2017-05-17 11:41 UTC by Anthony1911

No instant direction changes, to avoid breaking of fragile 3D printed gear

2017-05-17 20:03 UTC, timjon requested changes

2017-05-17 20:03 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
>                  delay(300);
Whats the point of keeping this delay?

2017-05-17 20:03 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +               // motor.write(START_POSITION_MOTOR_SERVO +30);
check row 408, and has this been tested?

2017-05-18 14:27 UTC, timjon approved these changes
Should be fine now

2017-05-18 14:58 UTC, Sebastian-Fransson approved these changes
Maybe remove the commented out stuff?

2017-05-19 10:06 UTC, IsabelleTornqvist approved these changes

2017-05-19 10:15 UTC, merged