Added modified collision control support
DIT524-V17/group-7 pull request #30
Opened 2017-05-23 15:53 UTC by Anthony1911

Now supports three HC SR04s in the front and one in the back for improved collision prevention.

2017-05-24 12:40 UTC, timjon requested changes
Ill make this request first before I take a second look

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +const int TRIG_PIN4 = A13;
Doesnt follow our standard for variable names

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +int ultrasonic_range_front;
add a "_middle" or something similar

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
>  boolean obstacle_detected;
Add a "_front" maybe

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> + if (voltage<voltage_Now){ //change global variable and send voltage to phone only when voltage drops
Why is the delay removed?

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    ultrasonic_range_front = ultrasonic_distance_string.toInt();
Why are you converting the long value to a string and then an int?

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        || flame_detected){ //flame
This if statement can and should be rewritten to be smaller and less complex

2017-05-24 12:40 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        if (ultrasonic_range_back != 0 && ultrasonic_range_back <= 50)   {
Why do you have a delay for the forward sensors but not this one?

2017-05-24 12:50 UTC, timjon requested changes

2017-05-24 12:50 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +            if ((!flame_detected && !obstacle_detected) || (velocity >= 90 && !obstacle_detected_back)){
Shouldnt both sides of the || check in the same way for both front and back?

2017-05-24 12:50 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    ultrasonic_distance_string = (String)sonars[0].ping_cm();
All collision things should be in a method

2017-05-24 12:55 UTC, timjon requested changes

2017-05-24 12:55 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +    ultrasonic_distance_string = "c" + ultrasonic_distance_string + '\n';
You are already doing this on line 408

2017-05-24 13:51 UTC, timjon requested changes

2017-05-24 13:51 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
>  @Version 1.2
Removed @Version 1.3 from the comment????

2017-05-24 13:51 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +            if ((!flame_detected && !obstacle_detected_front && velocity < 90) || (velocity > 90 && !obstacle_detected_back)){
Shouldnt it be "velocity > 90" in the first part?

2017-05-24 13:51 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        (ultrasonic_range_front_right != 0 && ultrasonic_range_front_right <= 25 ) ||
You dont have a delay for the ones on the side now

2017-05-24 13:51 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +            {
curly brackets?????

2017-05-24 13:51 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +        if (ultrasonic_range_back != 0 && ultrasonic_range_back <= 50)   {
Method maybe?

2017-05-24 15:16 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +const int TRIG_PIN_FRONT_MID = 4;
Why do all of them use Analog pins but the FRONT_MID one? Are we out of Analog pins? Backwards compatible?

2017-05-24 15:28 UTC, pontuslae requested changes
voltage_delay never increments anymore and a minor optimization change.

2017-05-24 15:28 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> + if (voltage<voltage_Now && voltage_delay >= 1000){ //change global variable and send voltage to phone only when voltage drops
voltage_delay never increments anymore

2017-05-24 15:28 UTC, pontuslae commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +void collisionControl() {
Don't ping sonars[0] twice, the value might change and each call to ping_cm() introduces a 20 microseconds delay.

2017-05-24 18:23 UTC, timjon requested changes

2017-05-24 18:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +            if ((!flame_detected && !obstacle_detected_front && velocity < 90) || (velocity > 90 && !obstacle_detected_back) || velocity== 90){
What does this line do? comment please

2017-05-24 18:23 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +      //Is true if the range in front is less than 50 cm, front left and front right - less than 25 cm or if the flame sensor has set the flame variable to true
Method maybe?

2017-05-25 19:24 UTC, Anthony1911 commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> +const int TRIG_PIN_FRONT_MID = 4;
We are indeed out of Analog pins because of advanced flame sensor.

2017-05-26 12:19 UTC, timjon requested changes

2017-05-26 12:19 UTC, timjon commented on SmartCar/Arduino/sketch_main/sketch_main.ino
> + if (voltage<voltage_Now && ++voltage_delay >= 1000){ //change global variable and send voltage to phone only when voltage drops
The delay should be in the main loop

2017-05-26 13:26 UTC, pontuslae approved these changes

2017-05-26 14:00 UTC, timjon approved these changes

2017-05-26 14:34 UTC, Sebastian-Fransson approved these changes
Goods enough

2017-05-26 14:35 UTC, merged