Raspberry files. PYthon3 integration, Multi socket, Camera feed
DIT524-V17/group-7 pull request #34
Opened 2017-05-26 14:56 UTC by pontuslae

2017-05-26 15:39 UTC, timjon requested changes

2017-05-26 15:39 UTC, timjon commented on TCP raspberry/receiver.py
> +import __future__
Remove if its not used

2017-05-26 15:39 UTC, timjon commented on TCP raspberry/receiver.py
> +coding = 'utf-8' # 'ISO8859-1'
Why does it say 'ISO8859-1' in a comment here?

2017-05-27 08:26 UTC, pontuslae commented on TCP raspberry/receiver.py
> +coding = 'utf-8' # 'ISO8859-1'
Because we changed encoding method several times. And remembering ISO8859-1 is hard.

2017-05-27 08:27 UTC, pontuslae commented on TCP raspberry/receiver.py
> +import __future__
It's called **Future**proofing 🥇

2017-05-27 08:34 UTC, timjon approved these changes

2017-05-27 10:09 UTC, merged